"""Generate docs/NEURONS.md (and the committed lock file) from flybrain/neurons.py.

    uv run --no-sync flybrain neurons-doc --refresh-lock   # needs the downloaded annotation table + connectome
    uv run --no-sync flybrain neurons-doc                  # re-render the doc from the lock (no data needed)
    uv run --no-sync flybrain neurons-doc --check          # CI: doc and lock are in sync with neurons.py
"""

from __future__ import annotations

import json
import sys

import numpy as np

from flybrain import neurons
from flybrain.config import repo_root


def doc_path():
    return repo_root() / "docs" / "NEURONS.md"


def build_lock() -> dict:
    import pandas as pd

    from flybrain import data_manifest
    from flybrain.connectome import load_connectome

    path = data_manifest.ensure("flywire_annotations", log=lambda _m: None)
    ann = pd.read_csv(path, sep="\t", dtype={"root_id": "Int64", "supervoxel_id": "Int64"}, low_memory=False)
    conn = load_connectome("flywire783")
    side_of = dict(zip(ann["root_id"].astype("int64"), ann["side"].fillna(""), strict=True))

    lock: dict = {
        "annotation_source": neurons.ANNOTATION_SOURCE,
        "annotation_sha256": data_manifest.load_manifest()["flywire_annotations"].sha256,
        "connectome": conn.name,
        "sets": {},
        "wiring": {},
    }
    for s in neurons.SETS:
        ids = neurons.resolve_in_table(s, ann)
        if len(ids) != s.expected_count:
            raise SystemExit(f"{s.name}: query matched {len(ids)} neurons, expected {s.expected_count}")
        sides = [side_of[int(i)] for i in ids]
        lock["sets"][s.name] = {
            "query": s.query,
            "count": len(ids),
            "in_connectome": int(np.isin(ids, conn.root_ids).sum()),
            "left": sides.count("left"),
            "right": sides.count("right"),
            "ids": [str(i) for i in ids],  # strings: root ids exceed 2^53
        }

    gf = conn.index_of(neurons.resolve_in_table(neurons.SET_BY_NAME["GF"], ann))
    gf_side = [side_of[int(i)] for i in conn.root_ids[gf]]
    for name in ("LC4", "LPLC2", "LPLC1", "LC6"):
        pre = conn.index_of(neurons.resolve_in_table(neurons.SET_BY_NAME[name], ann))
        rows = []
        for g, side in zip(gf, gf_side, strict=True):
            mask = conn.edge_mask(pre_idx=pre, post_idx=[g])
            w = conn.weight[mask]
            sign = "none" if w.size == 0 else ("excitatory" if (w > 0).all() else "mixed/inhibitory")
            rows.append(
                {
                    "gf_side": side,
                    "presynaptic_neurons": len(np.unique(conn.pre[mask])),
                    "synapses": int(np.abs(w).sum()),
                    "sign": sign,
                }
            )
        lock["wiring"][f"{name}->GF"] = rows
    gf_in = conn.weight[conn.edge_mask(post_idx=gf)]
    lock["wiring"]["GF_total_input"] = {
        "presynaptic_neurons": len(np.unique(conn.pre[conn.edge_mask(post_idx=gf)])),
        "excitatory_synapses": int(gf_in[gf_in > 0].sum()),
        "inhibitory_synapses": int(-gf_in[gf_in < 0].sum()),
    }
    return lock


def render(lock: dict) -> str:
    out = [
        "# Neurons",
        "",
        "Generated by `flybrain neurons-doc` from `brain/flybrain/neurons.py` and "
        "`brain/flybrain/data/neuron_sets.lock.json` — do not edit by hand.",
        "",
        f"Annotation source: {lock['annotation_source']} (file SHA-256 `{lock['annotation_sha256'][:16]}…`). "
        f"Connectome: `{lock['connectome']}`. Root IDs are FlyWire materialization 783 unless stated otherwise.",
        "",
        "## Sets defined by an annotation query",
        "",
        "| set | role | query | neurons (L / R) | in connectome | citation |",
        "|---|---|---|---:|---:|---|",
    ]
    for s in neurons.SETS:
        e = lock["sets"][s.name]
        out.append(
            f"| `{s.name}` | {s.role} | `{s.query}` | {e['count']} ({e['left']} / {e['right']}) | "
            f"{e['in_connectome']} | {s.citation} |"
        )
    out += ["", "### Why each set is used", ""]
    out += [f"- **{s.name}** — {s.rationale}" for s in neurons.SETS]
    out += ["", "### Root IDs of the small sets", ""]
    for s in neurons.SETS:
        e = lock["sets"][s.name]
        if e["count"] <= 4:
            out.append(f"- `{s.name}`: " + ", ".join(f"`{i}`" for i in e["ids"]))
    out += [
        "",
        "## Looming → Giant Fiber wiring measured in the connectome",
        "",
        "Counts come from the FlyWire 783 connectivity used by the model (automatic synapse detection), per Giant "
        "Fiber. For comparison, manual tracing in FAFB (Ache et al. 2019, right hemisphere) found 55 LC4 neurons / "
        "2,442 synapses and 108 LPLC2 neurons / 1,366 synapses onto one GF.",
        "",
        "| pathway | GF side | presynaptic neurons | synapses | sign in the model |",
        "|---|---|---:|---:|---|",
    ]
    for key, rows in lock["wiring"].items():
        if key == "GF_total_input":
            continue
        for row in rows:
            out.append(
                f"| {key} | {row['gf_side']} | {row['presynaptic_neurons']} | {row['synapses']:,} | {row['sign']} |"
            )
    t = lock["wiring"]["GF_total_input"]
    out += [
        "",
        f"All inputs to the two GFs together: {t['presynaptic_neurons']:,} presynaptic neurons, "
        f"{t['excitatory_synapses']:,} excitatory and {t['inhibitory_synapses']:,} inhibitory synapses.",
        "",
        "## Sets defined by published root IDs",
        "",
        "| set | materialization | neurons | citation | why |",
        "|---|---|---:|---|---|",
    ]
    for p in neurons.PUBLISHED:
        out.append(f"| `{p.name}` | {p.materialization} | {len(p.ids)} | {p.citation} | {p.rationale} |")
    out += ["", "Published MN9 IDs (783): " + ", ".join(f"`{i}`" for i in neurons.MN9_783.ids) + ".", ""]
    return "\n".join(out)


def main(*, check: bool, refresh_lock: bool) -> int:
    if refresh_lock:
        lock = build_lock()
        neurons.LOCK_PATH.parent.mkdir(parents=True, exist_ok=True)
        neurons.LOCK_PATH.write_text(json.dumps(lock, indent=1) + "\n", encoding="utf-8", newline="\n")
        print(f"wrote {neurons.LOCK_PATH}")
    lock = neurons.load_lock()
    problems = []
    for s in neurons.SETS:
        e = lock["sets"].get(s.name)
        if e is None or e["query"] != s.query or e["count"] != s.expected_count:
            problems.append(f"lock entry for {s.name} does not match neurons.py (run --refresh-lock)")
    text = render(lock)
    if check:
        current = doc_path().read_text(encoding="utf-8") if doc_path().exists() else ""
        if current != text:
            problems.append("docs/NEURONS.md is stale (run `flybrain neurons-doc`)")
    for msg in problems:
        print(msg, file=sys.stderr)
    if problems:
        return 1
    if check:
        print("docs/NEURONS.md and the lock file are in sync with neurons.py")
        return 0
    doc_path().write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {doc_path()}")
    return 0
